PDB Output: Fix a regression in calibre 9.0 that broke output to PDB/TCR/zTXT files. Fixes #2142195 [AttributeError: 'OptionValues' object has no attribute 'use_alt_text_for_images'](https://bugs.launchpad.net/calibre/+bug/2142195)